/**
 * Top Movies - OpenAPI 3.0
 * Top Movies Openapi spec.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: marom83@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    id?: number;
    username?: string;
    password?: string;
}